"""Builds FRENCH_REVIEW.md straight from the shipped XML (TRANSLATIONS.md section 3, "Review
file"). No hand-typing: the table cells are read, never retyped, so they cannot drift from the
mod. Run: uv run python Tests/generate_french_review.py
"""
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def revision():
    try:
        out = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
        dirty = subprocess.run(["git", "status", "--porcelain"], cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
        return out + (" + uncommitted changes" if dirty else "")
    except Exception:
        return "unknown (git unavailable)"


def keyed(path):
    result = {}
    for f in sorted(path.glob("*.xml")):
        for e in ET.parse(f).getroot():
            if isinstance(e.tag, str):
                result[e.tag] = e.text or ""
    return result


def def_field(root_defs_dirs, def_name, field_path):
    """Resolve DEFNAME.field.path against the shipped Defs/*.xml. field_path segments are
    element tags; a numeric segment is a 1-based <li> index inside the previous element."""
    for defs_dir in root_defs_dirs:
        for f in sorted(defs_dir.glob("*.xml")):
            for d in ET.parse(f).getroot():
                if d.findtext("defName") != def_name and d.get("Name") != def_name:
                    continue
                node = d
                for seg in field_path:
                    if seg.isdigit():
                        lis = node.findall("li")
                        idx = int(seg) - 1
                        if idx >= len(lis):
                            return None
                        node = lis[idx]
                    else:
                        nxt = node.find(seg)
                        if nxt is None:
                            return None
                        node = nxt
                return (node.text or "").strip()
    return None


def def_injected_table(fr_path, defs_dirs):
    rows = []
    for f in sorted(fr_path.glob("*.xml")):
        for e in ET.parse(f).getroot():
            if not isinstance(e.tag, str):
                continue
            def_name, *field_path = e.tag.split(".")
            english = def_field(defs_dirs, def_name, field_path)
            rows.append((e.tag, english, e.text or ""))
    return rows


def rule_strings(defs_file, pack_def_name):
    for d in ET.parse(defs_file).getroot():
        if d.tag == "RulePackDef" and d.findtext("defName") == pack_def_name:
            return [li.text for li in d.findall("rulePack/rulesStrings/li")]
    return []


def fr_rule_strings(fr_file, pack_def_name):
    root = ET.parse(fr_file).getroot()
    node = root.find(f"{pack_def_name}.rulePack.rulesStrings")
    if node is None:
        return []
    return [li.text for li in node.findall("li")]


def md_table(rows, headers=("Key or path", "Original", "English", "French")):
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        cells = [(c if c is not None else "*(no English DefInjected/source value found)*").replace("\n", "<br>").replace("|", "\\|") for c in row]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


out = []
out.append("# French review\n")
out.append(
    "Generated by `Tests/generate_french_review.py` from the shipped XML — never hand-edited.\n"
    "Regenerate whenever a French or English text changes; a stale copy is a defect "
    f"(TRANSLATIONS.md section 3).\n\nRevision: `{revision()}`\n"
)
out.append(
    "No source-language original: this mod is not a port from another language, so the "
    "Original column repeats the English text.\n"
)

# --- Keyed ---
en_keyed = keyed(ROOT / "Mod/Languages/English/Keyed")
fr_keyed = keyed(ROOT / "Mod/Languages/French/Keyed")
out.append("\n## Keyed (Mod/Languages/{English,French}/Keyed/NeverOutOfPrint.xml)\n")
out.append(md_table([(k, en_keyed.get(k, ""), en_keyed.get(k, ""), fr_keyed.get(k, "")) for k in en_keyed]))

# --- DefInjected ---
defs_dirs = [ROOT / "Mod/Defs"]
def_injected_sources = [
    ("ThingDef", ROOT / "Mod/Languages/French/DefInjected/ThingDef"),
    ("RecipeDef", ROOT / "Mod/Languages/French/DefInjected/RecipeDef"),
    ("ResearchProjectDef", ROOT / "Mod/Languages/French/DefInjected/ResearchProjectDef"),
    ("SpecialThingFilterDef", ROOT / "Mod/Languages/French/DefInjected/SpecialThingFilterDef"),
    ("WorkGiverDef", ROOT / "Mod/Languages/French/DefInjected/WorkGiverDef"),
    ("ThingDef (Ideology)", ROOT / "Mod/Ideology/Languages/French/DefInjected/ThingDef"),
    ("ThingCategoryDef (Ideology)", ROOT / "Mod/Ideology/Languages/French/DefInjected/ThingCategoryDef"),
    ("SpecialThingFilterDef (Ideology)", ROOT / "Mod/Ideology/Languages/French/DefInjected/SpecialThingFilterDef"),
]
for label, fr_path in def_injected_sources:
    if not fr_path.exists():
        continue
    rows = def_injected_table(fr_path, defs_dirs)
    if not rows:
        continue
    out.append(f"\n## DefInjected: {label}\n")
    out.append(md_table([(k, en, en, fr) for k, en, fr in rows]))

# --- Grammar rule packs (not resolved from a single symbol - flagged separately below) ---
out.append(
    "\n## Grammar: RulePackDef NeverOutOfPrint_Namer_IdeoligionBook / "
    "NeverOutOfPrint_Description_IdeoligionBook\n\n"
    "English source: `Mod/Defs/RulePacks.xml`. French: "
    "`Mod/Ideology/Languages/French/DefInjected/RulePackDef/NeverOutOfPrint.xml`.\n\n"
    "**Not a line-for-line translation, on purpose** (translator's note in the French file): "
    "the game's grammar resolver cannot accord gender or elide an article for a generated "
    "ideoligion name, so the French list drops constructions the English list uses "
    "(`[IDEO_name] and the [Character]`, `[IDEO_name] in the [TerrainFeature]`, "
    "`Our [ConceptAny], Their [ConceptAny]`) and adds one that avoids the problem "
    "(`Les nôtres, les leurs`). Counts differ between the two languages by design; the tables "
    "below are listed separately rather than paired row-by-row, so a count mismatch is not "
    "itself a finding.\n"
)
for pack in ("NeverOutOfPrint_Namer_IdeoligionBook", "NeverOutOfPrint_Description_IdeoligionBook"):
    en_rules = rule_strings(ROOT / "Mod/Defs/RulePacks.xml", pack)
    fr_rules = fr_rule_strings(ROOT / "Mod/Ideology/Languages/French/DefInjected/RulePackDef/NeverOutOfPrint.xml", pack)
    out.append(f"\n### {pack} — English ({len(en_rules)} rules)\n")
    out.append(md_table([(f"rule {i+1}", r, r, "") for i, r in enumerate(en_rules)]))
    out.append(f"\n### {pack} — French ({len(fr_rules)} rules)\n")
    out.append(md_table([(f"rule {i+1}", "", "", r) for i, r in enumerate(fr_rules)]))

out.append(
    "\n## Flagged for review\n\n"
    "Rows the session is unsure about (terminology, tone, or the 2026-09-30 gender-agreement "
    "rule — every French text agreeing with a pawn needs the three-segment "
    "`{PAWN_gender ? m : f : n}` switch):\n\n"
    "| Where | French text | Why flagged |\n|---|---|---|\n"
    "| `NeverOutOfPrint_IdeoligionBook.description` (Ideology DefInjected/ThingDef) | "
    "\"Un croyant qui lit le livre de sa propre foi en ressort plus assuré... un lecteur qui "
    "n'a plus de conviction du tout se convertit\" | Generic masculine noun+adjective (\"un "
    "croyant... assuré\") describing whoever reads the book. This is a static item description, "
    "not a string the engine resolves with a specific Pawn argument, so no `{PAWN_gender}` "
    "token is available to switch on — the question is whether the rule's intent still asks for "
    "a gender-neutral rewording here, or whether a static, unaddressed description is out of its "
    "scope. |\n"
    "| RulePackDef `NeverOutOfPrint_Description_IdeoligionBook`, French rules referencing "
    "\"le lecteur\" and \"un sceptique\" | e.g. \"que le lecteur a toutes les raisons d'être "
    "sceptique\", \"un dialogue entre un [IDEO_memberName] et un sceptique\" | Same question: "
    "these are rhetorical, generic figures in in-world book-blurb flavor text (matching the "
    "English `the reader`, which is itself ungendered), not a specific generated Pawn the grammar "
    "resolver tracks — no `PAWN_gender`-style symbol is available in this rule pack's scope "
    "(only `IDEO_*`, `ANYPAWN_*`, `worldname`, `date_season`). |\n"
)

Path(ROOT / "FRENCH_REVIEW.md").write_text("\n".join(out), encoding="utf-8")
print("wrote FRENCH_REVIEW.md")
