using System.Collections.Generic;
using System.Linq;
using HarmonyLib;
using RimWorld;
using Verse;

namespace NeverOutOfPrint
{
    /// <summary>
    /// A recipe's products are made from its product defs. A copy is not made from a def - it is
    /// made from the book that went in - so the copying recipes take over production entirely.
    /// Their <c>products</c> entry names a placeholder that never gets built.
    ///
    /// MakeRecipeProducts is an iterator; the prefix runs on the stub that hands back the state
    /// machine, so setting __result and returning false substitutes the whole sequence. That also
    /// skips GenRecipe.PostProcessProduct, which is the point: a copy must not have its quality
    /// re-rolled from the printer's skill or be recorded as their handiwork.
    /// </summary>
    [HarmonyPatch(typeof(GenRecipe), nameof(GenRecipe.MakeRecipeProducts))]
    internal static class Patch_GenRecipe_MakeRecipeProducts
    {
        private static bool Prefix(ref IEnumerable<Thing> __result, RecipeDef recipeDef, List<Thing> ingredients)
        {
            if (recipeDef?.workerClass != typeof(RecipeWorker_CopyBook))
            {
                return true;
            }

            Book source = ingredients?.OfType<Book>().FirstOrDefault();
            if (source == null)
            {
                Log.Error("[Never Out of Print] " + recipeDef.defName + " finished with no book among its ingredients; nothing printed.");
                __result = Enumerable.Empty<Thing>();
                return false;
            }

            int count = recipeDef.products?.FirstOrDefault()?.count ?? 1;
            var copies = new List<Thing>(count);
            for (int i = 0; i < count; i++)
            {
                Book copy = BookCopyUtility.MakeCopy(source);
                if (copy != null)
                {
                    copies.Add(copy);
                }
            }

            __result = copies;
            return false;
        }
    }

    /// <summary>
    /// A book written at a bench is generated by CompQuality.SetQuality, which calls
    /// Verse.Book.GenerateBook with no author - so an ideoligion book written by a colonist would
    /// argue for a faith picked at random rather than for theirs. Regenerating it with the worker
    /// named puts that right, and rewrites the title and blurb to match.
    ///
    /// Scoped to this mod's book on purpose. Doing it for every book would re-roll what other mods
    /// have just deliberately set on theirs.
    /// </summary>
    [HarmonyPatch(typeof(GenRecipe), "PostProcessProduct")]
    internal static class Patch_GenRecipe_PostProcessProduct
    {
        private static void Postfix(Thing __result, Pawn worker)
        {
            if (__result is IdeoligionBook book && worker?.Ideo != null)
            {
                book.GenerateBook(worker);
            }
        }
    }

    /// <summary>
    /// Steers a "copy book with fewest copies" bill towards the book it is actually for.
    ///
    /// Which book a bill reaches for is chosen by the ingredient finder, which knows only that any
    /// allowed book will do. Without this the bill would count copies of the scarcest title and
    /// then cheerfully print another of whichever book happened to be nearest, and never catch up.
    /// The candidate list is narrowed to the works currently tied for fewest copies, and the
    /// ordinary ingredient search picks the closest of those.
    ///
    /// The answer is cached for the tick it was computed in: the finder is called repeatedly while
    /// a colonist looks for work, and scanning every book on the map each time is what made the
    /// bill expensive in the first place.
    /// </summary>
    [HarmonyPatch(typeof(WorkGiver_DoBill), "TryFindBestBillIngredientsInSet_NoMix")]
    internal static class Patch_WorkGiver_DoBill_NoMix
    {
        private static Map cachedMap;
        private static int cachedTick = -1;
        private static Bill cachedBill;
        private static List<BookKey> cachedKeys = new List<BookKey>();

        private static void Prefix(List<Thing> availableThings, Bill bill)
        {
            if (!(bill is Bill_Production production) ||
                production.recipe?.workerCounterClass != typeof(RecipeWorkerCounter_CopyBookFewest))
            {
                return;
            }

            List<BookKey> keys = KeysForBill(production);
            availableThings.RemoveAll(thing => thing is Book && !keys.Contains(BookKey.For(thing)));
        }

        private static List<BookKey> KeysForBill(Bill_Production bill)
        {
            if (bill == cachedBill && bill.Map == cachedMap && GenTicks.TicksAbs == cachedTick)
            {
                return cachedKeys;
            }

            cachedBill = bill;
            cachedMap = bill.Map;
            cachedTick = GenTicks.TicksAbs;
            cachedKeys = RecipeWorkerCounter_CopyBookFewest.LeastCopiedWorks(bill, out int _);
            return cachedKeys;
        }
    }
}
